services:
  - type: web
    name: multi-purpose-agent
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend_with_mcp.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: MCP_API_KEY
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
      - key: LANGSMITH_TRACING
        value: "false"
      - key: LANGSMITH_PROJECT
        value: "CHATBOT"
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX
        value: "mychatbot"
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_PORT
        value: "5432"
      - key: POSTGRES_DB
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
